### ISSUE TITLE
Tests fail for zlib 1.3

### ISSUE THREAD

**Issue by luau-project** [brimworks/lua-zlib#70]
## Description

When the system has zlib 1.3 installed, ```lua-zlib``` tests (test.lua) fail on function ```test_version()``` at

[https://github.com/brimworks/lua-zlib/blob/b2f6db9956ec57993d4223ff35a94c15da03dd48/test.lua#L183](https://github.com/brimworks/lua-zlib/blob/b2f6db9956ec57993d4223ff35a94c15da03dd48/test.lua#L183)

because ```lua-zlib``` expects zlib version to be formatted as X.Y.Z, but zlib reports 1.3.

> [!NOTE]
> 
> This issue affects every Ubuntu 24.04 user (current LTS), because Ubuntu 24.04 ships zlib 1.3.

## Reproduction

I wrote a GitHub workflow to reproduce this issue using two zlib versions (1.3.1 and 1.3). In the screenshot below, it can be seen that tests ran fine for zlib 1.3.1, but failed for zlib 1.3:

![Image](https://github.com/user-attachments/assets/0ccbe2df-8dd9-4a88-bd65-bd92e70e0a20)

You can check the runs on a branch that I created just for the issue reproduction (login to GitHub and browse [https://github.com/luau-project/lua-zlib/actions/runs/14003832351](https://github.com/luau-project/lua-zlib/actions/runs/14003832351)). In case you want to run the workflow yourself, just paste the following yaml code in the expandable section below on a file named ```.github/workflows/test-version-issue.yml``` and push it on a new branch on your fork.

<details>
<summary>Expand here to see the workflow</summary>

```yaml
name: test_version issue

on: [push, pull_request]

jobs:
  issue-reproduction:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        zlibVersion: ["1.3.1", "1.3"]
        luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download, extract, configure, build and install zlib
        run: |
          wget https://zlib.net/fossils/zlib-${{ matrix.zlibVersion }}.tar.gz
          tar -xf zlib-${{ matrix.zlibVersion }}.tar.gz
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -S zlib-${{ matrix.zlibVersion }} \
            -B build-zlib
          cmake --build build-zlib
          sudo cmake --install build-zlib
          sudo ldconfig

      - name: Setup ‘lua’
        uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup ‘luarocks’
        uses: luarocks/gh-actions-luarocks@v5

      - name: Build lua-zlib
        run: luarocks make rockspecs/lua-zlib-1.2-2.rockspec

      - name: Run test
        run: lua test.lua
```
</details>
